### ISSUE TITLE
Responsiveness of the website

### ISSUE THREAD

**Issue by Namanb454** [AkashChetia/weblamp#9]
Issue:

- The site is not responsive for the mobile application.

Proposal:

- I will make the site responsive for both mobile and window application.

**Comment by Namanb454** [comment]
@AkashChetia Please assign this issue to me.

**Comment by AkashChetia** [comment]
@Namanb454 sure, you can go ahead!

**Comment by Namanb454** [comment]
@AkashChetia  Thank you so much.
I will provide you the solution as soon as possible
